[package]
name = "blackjack"
version = "0.1.0"
authors = ["Orlyn Gerano <orlyn_gerano@yahoo.com>"]
edition = "2018"

[dependencies]
clap = { version = "4.0.32", features = ["derive"] }
colored = "3.1.1"
rand = "0.9.2"
